### PR TITLE
iOS: add missing linker flags to preserve categories methods in the linked binary

### PR DESCRIPTION
**Pull request by gelosi**
Hello,

There's always a problem with iOS simulator using google toolbox -> app crashes with missing categories for NS*** classes.

Problem is missing liker flag -ObjC

### CODE REVIEW

**Comment by gelosi** [comment]
I signed it!)

**Comment by thomasvl** [comment]
I can see potentially adding `-ObjC`, but `-all_load` is kinda dangerous and something a developer should decide on their own to do because it defeats dead stripping of any C or C++ code they also may happen to be linking.

**Comment by thomasvl** [comment]
So `-ObjC` forces all categories and classes in, reality is this likely won't be bad, because most people end up using it, but we haven't added this to the xcconfig before now and let developers do it to their project when they are sure they want the behavior instead of forcing it.

The issue you seem to be concerned about isn't going to be specific to the simulator like you mentioned, it should happen for any platform.  So there's sorta two questions: should we really force this vs. leaving it up to developers to do on their own projects/targets (they might use the xcconfigs but not use any categories coming from other static libs); and if we do this, should we do it for all platforms or just a subset.

**Comment by gelosi** [comment]
@thomasvl I've checked more the use cases for iOS, and this toolbox is used for GTMSessionFetcher for instance (which is sub-dependency for Firebase...). So, basically, impacts a set of products. If you thinking about delegation of the decision to the developers – it's direct. Mostly because people use the categories from it. So, finding one is missing from the binary is a nasty surprise. 
A difficulty here is – some frameworks are distributed with precompiled binary, some as src. And it's only for src case possible to find out there's missing code at the compile stage (with default linker settings). 
To be honest, I don't know if there's a better solution, and my intent is to make use of 3rd-party  frameworks less painful. 
Of course, if you use toolbox directly – the code will be compiled in the binary, but in case of indirect use (as a subspec of something) – we're hitting the undefined state. (Turned out to be a long-running problem for firebase auth on simulator for instance) And this is a reason why I've sent this request.

**Comment by thomasvl** [comment]
Doesn't Firebase use things via pods so it won't use the xcconfigs?  The only folks this should impact is someone using the xcconfigs in their own projects, right?

**Comment by gelosi** [comment]
yepp, it's different MR (hopefully not, as it seems like since v. 5.0 firebase works well via cocoapods)

**Comment by gelosi** [comment]
Thanks!

**Comment by BRIANREINWALd** [comment]
Thanks

**Comment by coreyandersonbuilders** [comment]
Hang on tight ladies and punkdustind law enforcement is involved I’m now giving you a last chance to come clean at my moms @11:45pm or face charges

**Pull request closed without merging**
