### PR TITLE
Fixed PodSpec for tvOS

### PR DESCRIPTION
**Pull request by mariohahn**

### CODE REVIEW

**Comment by mariohahn** [comment]
I rechecked it now: 

```json
{
      "name": "AddressBook",
      "source_files": "AddressBook/GTMABAddressBook.{h,m}",
      "frameworks": "AddressBook",
      "dependencies": {
        "GoogleToolboxForMac/Core": [
          "2.1.1"
        ],
        "GoogleToolboxForMac/Defines": [
          "2.1.1"
        ]
      },
      "platforms": {
        "ios": "5.0",
        "osx": "10.6"
      }
    }
```
Now iOS and OS X is included

**Comment by thomasvl** [comment]
Interesting, the docs don't give any hit this would work, and even document it only takes one value.  Is there something we can throw in a comment as to where this came from incase it has to get revisited in the future?

**Comment by mariohahn** [comment]
Pod spec lint was successfully and  pod ipc spec returned to correct json. 

I just thought it should work because they have the options as array for all plurals like platform"s". 

But I haven't found it in the documentation too.

**Comment by dengm129** [comment]
#140

**Pull request merged**
