### PR TITLE
Bazel BUILD: Make targets corresponding to pod suspsecs publicly visible and usable.

### PR DESCRIPTION
**Pull request by cpsauer**
Thanks again, @maxwellE for the great work in #280! This is just a quick patch to make targets visible for outside use.

Could I get a review @thomasvl?

### CODE REVIEW

**Comment by cpsauer** [comment]
Also, @thomasvl, while you're reading this:

For my future learning (and curiosity), what's the mechanism by which the + breaks usage from Swift?

Is it that Swift doesn't accept .a's with + in their names? Auto-substitutes _ for +? Something else? Saw those in your code review feedback to @maxwellE and wanted to learn.

**Comment by cpsauer** [comment]
One more thing for the batch: @thomasvl, would you accept a PR for a build file for https://github.com/google/gtm-session-fetcher? 

No pressure, ofc, but I've written half of one for our internal uses, and it'd be easy to flesh it out if you wanted it.

**Comment by thomasvl** [comment]
> For my future learning (and curiosity), what's the mechanism by which the + breaks usage from Swift?
> 
> Is it that Swift doesn't accept .a's with + in their names? Auto-substitutes _ for +? Something else? Saw those in your code review feedback to @maxwellE and wanted to learn.

This, `+` isn't valid in a module name.  _rules_swift_ will substitute it for an `_`, but since you can't just open the BUILD file and copy.paste the name, it seems safer to avoid those names.

**Review by thomasvl — APPROVED** [review]

**Comment by cpsauer** [comment]
Awesome. Thanks @thomasvl for teaching and for such a quick review!

(I'm assuming that's a no for gtm-session-fetcher BUILD, but lmk if you do want them.)

**Comment by thomasvl** [comment]
> (I'm assuming that's a no for gtm-session-fetcher BUILD, but lmk if you do want them.)

Sorry, forgot to comment on that, that's fine.  Same thing about adding a CI setup, etc.

**Pull request merged**
