### PR TITLE
Bazel: Improve dependency situation per #410

### LINKED ISSUE #410: Bazel dependencies issues
Hi wonderful Googlers,

I was debugging something else and noticed some potential problems in the bazel dependencies https://github.com/google/google-toolbox-for-mac/blob/main/bazel_support/repositories.bzl

1. The rules_cc version in there is super old--old enough that it can break some other things that depend on it. I think the solution, though, is probably to just eliminate it rather than update, since it looked like it was only used for objc_library, and my understanding is that Bazel had fallen back to just having people use the one that was automatically loaded rather than the one from rules_cc.
2. rules_apple needs to load a bunch of transitive dependencies and is also *very* old. (See release snippet [here](https://github.com/bazelbuild/rules_apple/releases/tag/3.1.1)). You could   have users call a bunch of layers of dependency macros...but it might be easier to just scrap all this dependency pulling and just tell people to get rules_apple. If they're using this, they're probably already pulling it in. 

TL;DR recommend emptying google_toolbox_for_mac_rules_dependencies, since the contents are super out of date and probably not worth it. (But keep the empty function around in case you need it in the future--and to avoid breaking existing users.)

Thoughts?

Thanks for all you do,
Chris
(ex-Googler)

### PR DESCRIPTION
**Pull request by cpsauer**
Fixes #410

### CODE REVIEW

**Comment by cpsauer** [comment]
(Failure is test infra failing to install bazelisk; will give a quick attempt at fixing.)

**Review by thomasvl — APPROVED** [review]
Thank you!

(nice that the github images include bazel now)

**Comment by cpsauer** [comment]
Thank you, Thomas! :)

**Comment by cpsauer** [comment]
While we're both here, a couple other upcoming Bazel things in my head that it occurred you might want a heads up on:
(1) As we get towards Bazel 7, the (Google) Bazel folks are likely to step up pressure to support bzlmod, their new package manager, which would require submitting PRs on each release. I've heard this is automatable with https://github.com/bazel-contrib/publish-to-bcr, but I'm not an expert yet.
(2) The rules_apple for internal development will, ofc, get out of date as time goes on. We could set up Renovate to auto-update it, so you can forget about it, as many Bazel repos have done. But I think only you can add GitHub apps, so you'd need to lead. I'd be happy to help with the config, though. Lmk if you want help there. All that benefit is probably fairly limited. On one hand it'll stop CI from ever breaking if rules_apple needs changes in step with Bazel. On the other, it has no impact on users since it's just the rules_apple version for tests; users are getting their own.

**Comment by thomasvl** [comment]
1. bzlmod seems like a direction we should move, rules_apple, rules_swift, apple_support seem to have already support it, so that likely could be done at any point.
2. I don't have any experience with Renovate.  Could a github action that is set to run once a month be used to check and see if it time to update?  I guess the best option would be something that would propose a PR to be approve when there was something to update.

**Comment by cpsauer** [comment]
1. Great! In that case, here's #412, switching to bzlmod for building within this project, paving the way for you to do central repository releases whenever you're ready. 
I already had, in my head, a good idea of how we should do that part, so I figured I'd just knock it out. Unfortunately still don't have experience with the release automation stuff, but maybe we can share notes when either of us gets there on our projects :)
2. Renovate does exactly that by default: proposing PRs when there's something to update. (It can also auto-merge if checks pass--or do all that with branches to save you the email spam, which is what I'd advise, falling back to PRs if things fail.) It's used in lots of Bazel projects (including first-party) and is awesome, IMO. If you're interested, just add the app https://github.com/apps/renovate and I can help with config.

**Comment by thomasvl** [comment]
Since Renovate wants r/w permissions that's likely a no go for google repos.  If you see something like that on another google repo, that's a pretty good sign it could be used here.

**Comment by cpsauer** [comment]
I'm pretty sure it's used in a bunch of Google repos--let me dig real quick

**Comment by cpsauer** [comment]
Yeah, sure is. If useful, here's a google org repo example: https://github.com/google/osv-scanner

And here's a bazelbuild org one https://github.com/bazelbuild/rules_kotlin

**Comment by cpsauer** [comment]
(I can see from their renovate.json files -- though I'd recommend renovate.json5)

(Could also use "Forking Renovate" which [doesn't ask for code write permissions](https://docs.renovatebot.com/security-and-permissions/), but then also omits some of the most convenient auto-merge options. I haven't actually used that variant; I've always wanted the other features.)

**Comment by thomasvl** [comment]
I think I have the app installed (it send a PR to start), haven't tried to look at tuning the config once this first PR is merged.

**Comment by cpsauer** [comment]
Great! Lmk if you'd like my help configuring. Could, e.g. turn on silent auto-merge for rules_apple with

```json5
  "packageRules": [{ // If you want a package to update on autopilot and, whitelist it here avoid having automated PRs to review.
    "automerge": true, // Just automatically propose and merge in dependency upgrades to the latest.
    "automergeType": "branch", // No PR unless tests fail; just do it.
    "matchPackageNames" : [ // Add Bazel name= parameter here.
      "rules_apple",
    ],
  }],

```
(IMO json->json5 is also fairly worth it for comments and allowing trailing commas to reduce diffs and issues there.)

**Comment by thomasvl** [comment]
Thanks, I think we'll keep it manual merges, we can always revisit that in the future.  Probably doesn't hurt to let it keep an eye on the github workflow files.

**Comment by cpsauer** [comment]
Sure! Totally up to you, of course. Just want to make sure I'm making easy all the things I wish someone had told me when I got going with it. Thanks, Thomas!

**Pull request merged**
