### PR TITLE
Support for tvOS

### PR DESCRIPTION
**Pull request by mariohahn**

### CODE REVIEW

**Comment by mariohahn** [comment]
I signed it!

**Comment by mariohahn** [comment]
the Swift Version file is needed for Cocoapods.

**Comment by thomasvl** [comment]
> the Swift Version file is needed for Cocoapods.

I thought that was only needed it the pod included Swift?

**Comment by mariohahn** [comment]
I thought that too, but pod spec lint was giving me the error that the swift versioning was missing

**Comment by thomasvl** [comment]
Huh, must me a newer requirement that we haven't hit yet.

**Comment by thomasvl** [comment]
fyi - working on pushing the updated spec live.

**Comment by mariohahn** [comment]
uhh wait a seconds..

I have recheck the podspec with pod ipc spec GoogleToolboxForMac.podspec 

I noticed that iOS is missing.

to have different platforms that seems not the right way because as you can see at the bottom he only uses that last -> OS X

```ruby 
    sp.platform = :ios
    sp.platform = :osx
```
```json
{
      "name": "AddressBook",
      "source_files": "AddressBook/GTMABAddressBook.{h,m}",
      "frameworks": "AddressBook",
      "dependencies": {
        "GoogleToolboxForMac/Core": [
          "2.1.1"
        ],
        "GoogleToolboxForMac/Defines": [
          "2.1.1"
        ]
      },
      "platforms": {
        "osx": "10.6"
      }
    }
```

You have an idea how to do that?

**Comment by thomasvl** [comment]
Aside: Looks like I also will have to cut a new version to push and update to the spec.

Looking at [the spec](https://guides.cocoapods.org/syntax/podspec.html#platform), it seems platform only allows one platform.  I see two possible way to hack around it:
1. Use `deployment_target` and set the tvOS one really high.
2. Use the [multiplatform support](https://guides.cocoapods.org/syntax/podspec.html#tvos), to only give the AddressBook subspec sources and a framework to link on iOS and macOS.  If the empty subspec chokes, it might take adding an individual source that is empty.

Hm, unless you can have two subspecs each named AddressBook, but each having a platform attribute.

**Pull request merged**
